name: Merge to stage
on:
  push:
    branches:
    - main
  workflow_dispatch: #run manually
jobs:
  log_time:
    name: log the time of push
    runs-on: ubuntu-latest
    environment: merge-to-stage

    steps:
    - name: echoing name
      run: echo sharath kannan

    - uses: actions/create-github-app-token@v1
      id: milo-pr-merge-token
      with:
        app-id: ${{ secrets.temp_PR_MERGE_APP_ID }}
        private-key: ${{ secrets.temp_PR_MERGE_PRIVATE_KEY }}
        
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: echo ${{ steps.milo-pr-merge-token.outputs.token }}
